version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - docker build -t health-check:latest .
      - docker tag health-check:latest 146747443241.dkr.ecr.ap-south-1.amazonaws.com/health-check:latest
  post_build:
    commands:
      - docker push 146747443241.dkr.ecr.ap-south-1.amazonaws.com/health-check:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' health-check 146747443241.dkr.ecr.ap-south-1.amazonaws.com/health-check:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

