version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 146747443241.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t health-check:latest .
      - docker tag health-check:latest 146747443241.dkr.ecr.ap-south-1.amazonaws.com/health-check:latest
  post_build:
    commands:
      - docker push 146747443241.dkr.ecr.ap-south-1.amazonaws.com/health-check:latest
      - printf '[{"name":"ALB-health-check","imageUri":"%s"}]' 146747443241.dkr.ecr.ap-south-1.amazonaws.com/health-check:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

